version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: parkchain_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: parkchain_db
      POSTGRES_USER: parkchain_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-parkchain_secure_pass}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parkchain_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parkchain_user -d parkchain_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: parkchain_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - parkchain_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  parkchain_network:
    driver: bridge